<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>TiaAutomationFactory.TiaV21Worker</RootNamespace>
    <AssemblyName>TiaV21Worker</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Siemens.Engineering.Base">
      <HintPath>C:\Program Files\Siemens\Automation\Portal V21\PublicAPI\V21\net48\Siemens.Engineering.Base.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Siemens.Engineering.Step7">
      <HintPath>C:\Program Files\Siemens\Automation\Portal V21\PublicAPI\V21\net48\Siemens.Engineering.Step7.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
